import {plans} from '@/lib/model';
const extras=[
 ['Skater keytag','$10–$20','Your physical rink keytag.','Published local examples: $10 at New Ulm, $15 at Pickwick, and $20 at RoseGarden. Retail price varies by rink.'],
 ['Additional rink access','$10 per added rink','Add another participating rink.','The published guide does not state whether this charge renews annually.'],
 ['Coach keytag','$60 · local example','A visiting-coach keytag at Park City.','A local club price, not a confirmed nationwide rate.'],
 ['RM-SBC console','Price not found','Rinkside music-selection and playback equipment.','Current equipment pricing requires a quote.'],
 ['RM-SBC mounting cradle','Price not found','A mounting cradle for the RM-SBC console.','Separate pricing versus bundled pricing is unknown.'],
 ['Installation & rink support','Not verified','Installation, rink software, and support services.','No public fee schedule was found in the supplied research.'],
 ['Stay Sharp Sparks gloves','$49.99 sale / $54.99 regular','Third-party gloves with an integrated chip described as compatible with RinkMusic.','Published third-party pricing supplied for this page; current price, stock, and compatibility need confirmation.']
];
export default function ProductsView(){return <div className="products-page"><header className="products-heading"><span className="eyebrow">RINKMUSIC / PRODUCTS & PRICING</span><h1>Your music.<br/>Your setup.</h1><p>Music plans for skaters. Keytags and equipment for the rink.</p></header><div className="notice"><span><strong>Published prices · Current checkout prices not verified</strong><br/>The annual plans below were identified as 2023 pricing by New Ulm Figure Skating Club. Local prices and third-party offers may differ today.</span></div><section aria-labelledby="music-plans"><div className="panel-heading"><h2 id="music-plans">Annual music subscriptions</h2><span className="pill">4 plans</span></div><div className="plans">{plans.map(p=><article key={p.name} className={`plan ${p.name==='Gold'?'featured':''}`}><span className="eyebrow">ANNUAL MUSIC PLAN</span><h2>{p.name}</h2><div className="price">${p.price}<span>/ year</span></div><p>Up to {p.songs} songs</p><a className={p.name==='Gold'?'primary full':'secondary full'} href="/skater/billing">Explore demo plans</a></article>)}</div><div className="panel products-plan-note"><h3>Room to change your routine.</h3><p>The published instructions say songs can be replaced during the year and members can upgrade by paying the difference. These are published terms, not a verified live checkout offer. Demo plan changes on this site do not collect payment.</p><a className="text-link" href="https://nuskate.org/rinkmusic/" target="_blank" rel="noopener noreferrer">Published pricing reference</a></div></section><section aria-labelledby="rink-products"><div className="panel-heading"><h2 id="rink-products">Keytags, rink access & equipment</h2></div><div className="product-service-grid">{extras.map(([title,price,description,note])=><article className="panel service-product" key={title}><span className="eyebrow">{title.includes('gloves')?'THIRD-PARTY ACCESSORY':title.includes('keytag')?'KEYTAG':title.includes('access')?'RINK ACCESS':'RINK EQUIPMENT & SERVICES'}</span><h3>{title}</h3><strong className="service-price">{price}</strong><p>{description}</p><div className="service-note">{note}</div></article>)}</div></section><aside className="panel products-bottom"><div><h2>Looking for your rink-day gear?</h2><p>The Glide Lab has accessories you can shop directly with the retailer.</p></div><a className="primary" href="/skater/store">Shop The Glide Lab</a></aside></div>}
