import {initialWorkspace,plans,rinks,type Workspace} from './model';
import {guides} from './guides';
function database():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open('rinkmusic-public-demo',1);r.onupgradeneeded=()=>{r.result.createObjectStore('data');r.result.createObjectStore('audio');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('Allow browser storage to save your demo.'));});}
async function read<T>(store:string,key:string):Promise<T|undefined>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readonly');const req=tx.objectStore(store).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close();});}
async function write(store:string,key:string,value:unknown){const db=await database();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(new Error('Could not save. Check available browser storage.'));};});}
export async function resolveAudio(id:string){const blob=await read<Blob>('audio',id);if(!blob)throw new Error('Audio unavailable in this browser.');return URL.createObjectURL(blob);}
export async function demoFetch(url:string,options?:RequestInit):Promise<Response>{try{
const data=await read<Workspace>('data','workspace')||initialWorkspace();
if(url==='/api/assistant'){const {message,role}=JSON.parse(String(options?.body));const q=String(message).toLowerCase();let id='account';if(/store|shop|glide|buy|bag|guard|affiliate/.test(q))id='store';else if(/upload|song|music|file/.test(q))id='music';else if(/tag|fob|lost|add.*rink/.test(q))id='rinks';else if(/plan|bill|pay|subscription/.test(q))id='plans';else if(/coach|priority|queue|note/.test(q))id='coaches';else if(/rink|partner|connect|assistant/.test(q))id='partners';const g=guides.find(g=>g.id===id)!;return Response.json({answer:[g.intro,...g.steps.map((s,i)=>`${i+1}. ${s}`),g.note].join('\n\n'),source:`/${['skater','coach','partner'].includes(role)?role:'skater'}/guides#${id}`,mode:'guided_preview'});}
if(url==='/api/audio'){const form=options?.body as FormData;const file=form.get('audio') as File;const title=String(form.get('title')||'').trim().slice(0,80);if(!file||!title)throw new Error('Choose an audio file and a title.');if(!/\.(mp3|wav|m4a)$/i.test(file.name)||file.size>15*1024*1024)throw new Error('Choose MP3, WAV, or M4A up to 15 MB.');if(data.music.length>=(plans.find(p=>p.name===data.plan)?.songs||5))throw new Error('Choose a larger demo plan.');const id=crypto.randomUUID();await write('audio',id,file);data.music.push({id,title,program:String(form.get('program')),duration:'Uploaded',color:'lime',uploaded:true});await write('data','workspace',data);return Response.json({data});}
if(url!=='/api/workspace')throw new Error('Live service not connected.');
if(options?.method==='POST'){const input=JSON.parse(String(options.body));const value=String(input.value??'').slice(0,2000);switch(input.action){case 'plan':if(!plans.some(p=>p.name===value))throw new Error('Unknown plan.');if(data.music.length>(plans.find(p=>p.name===value)?.songs||0))throw new Error('Not enough music slots.');data.plan=value;break;case 'renewal':data.renewal=value==='true';break;case 'rink':if(!rinks.some(r=>r.id===value))throw new Error('Unknown rink.');if(!data.rinks.includes(value))data.rinks.push(value);break;case 'tag':if(!/^[A-Z0-9-]{4,32}$/i.test(value))throw new Error('Use 4–32 letters, numbers, or dashes.');data.tag=value;break;case 'queue':{const track=data.music.find(t=>t.id===value);if(!track)throw new Error('Track not found.');if(data.queue.some(q=>q.name==='You'))throw new Error('You already have a program in this demo queue.');data.queue.push({id:crypto.randomUUID(),name:'You',program:track.program});break;}case 'removeQueue':data.queue=data.queue.filter(q=>q.id!==value);break;case 'priority':{const item=data.queue.find(q=>q.id===value);if(item)data.queue=[item,...data.queue.filter(q=>q.id!==value)];break;}case 'note':data.notes[value]=String(input.extra||'').slice(0,2000);break;case 'partner':if(!rinks.some(r=>r.id===value))throw new Error('Unknown rink.');data.partner=value;break;default:throw new Error('Unknown action.');}await write('data','workspace',data);}
return Response.json({data});}catch(e){return Response.json({error:e instanceof Error?e.message:'Unable to save.'},{status:400});}}
